package com.schoolsoft.rollover.internal;

import com.schoolsoft.tenancy.api.AcademicYearDto;
import com.schoolsoft.tenancy.api.NumberSeries;
import java.sql.Date;
import java.util.List;
import java.util.UUID;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

/**
 * What follows a child into the new year (YEC-06, FEE-16).
 *
 * Money, their bus seat, and the subjects they elected. Guardian links,
 * library dues and the student record itself need nothing done to them —
 * they hang off the student, not the enrolment, which is why they survive a
 * year boundary that enrolment-scoped things do not.
 *
 * Every row written here is recorded as a {@link RolloverRepository.Artifact},
 * so a roll-back removes precisely what the run made.
 */
@Service
public class CarryForward {

    private static final String ARREARS_HEAD_CODE = "ARREARS";

    private final JdbcTemplate jdbc;
    private final NumberSeries numbers;
    private final RolloverRepository repo;

    public CarryForward(JdbcTemplate jdbc, NumberSeries numbers, RolloverRepository repo) {
        this.jdbc = jdbc;
        this.numbers = numbers;
        this.repo = repo;
    }

    /**
     * Unpaid balances from the closing year become one opening-balance invoice
     * in the new one, and the old invoices are marked {@code carried_forward}.
     *
     * Marking them matters: leaving them open would count the same arrear twice
     * — once in the year the family did not pay it, once in the year they are
     * being asked for it — and the outstanding report would disagree with
     * itself.
     */
    public double carryArrears(UUID runId, UUID allocationId, UUID schoolId, UUID studentId,
                               AcademicYearDto from, AcademicYearDto to) {
        // Anything unpaid that was raised before the new year begins is an
        // arrear. An invoice generated by a billing run names its year; one
        // keyed in by the office often does not, and issue date is then the
        // only honest thing to go on — a bill raised in March for a family who
        // never paid it is exactly what a school means by "arrears".
        var open = jdbc.query(
            "SELECT fi.id, (fi.total - fi.paid) AS balance, fi.status FROM fee_invoice fi " +
            "WHERE fi.school_id = ? AND fi.student_id = ? " +
            "  AND fi.status IN ('open','partial','overdue') AND fi.total > fi.paid " +
            "  AND (fi.academic_year_id = ? " +
            "       OR (fi.academic_year_id IS NULL AND fi.issued_on < ?))",
            (rs, i) -> new Object[]{
                UUID.fromString(rs.getString("id")), rs.getDouble("balance"), rs.getString("status")
            },
            schoolId, studentId, from.id(), Date.valueOf(to.startsOn()));

        double total = open.stream().mapToDouble(row -> (Double) row[1]).sum();
        if (total < 0.005) return 0;

        UUID headId = arrearsHead(schoolId);
        UUID invoiceId = UUID.randomUUID();
        String invoiceNo = numbers.next(schoolId, NumberSeries.Kind.invoice, null, "OB{YY}{SEQ:5}", null);
        double rounded = Math.round(total * 100.0) / 100.0;

        jdbc.update(
            "INSERT INTO fee_invoice (id, school_id, student_id, academic_year_id, invoice_no, cycle_label, " +
            "  issued_on, due_on, subtotal, gst, total, status) " +
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0, ?, 'open')",
            invoiceId, schoolId, studentId, to.id(), invoiceNo,
            "Opening balance " + from.code(), Date.valueOf(to.startsOn()), Date.valueOf(to.startsOn()),
            rounded, rounded);
        jdbc.update(
            "INSERT INTO fee_invoice_line (id, fee_invoice_id, fee_head_id, description, amount) " +
            "VALUES (?, ?, ?, ?, ?)",
            UUID.randomUUID(), invoiceId, headId, "Arrears carried forward from " + from.code(), rounded);
        repo.recordArtifact(runId, allocationId, schoolId, "fee_invoice", invoiceId, null);

        for (Object[] row : open) {
            jdbc.update("UPDATE fee_invoice SET status = 'carried_forward', updated_at = now() WHERE id = ?",
                row[0]);
            repo.recordArtifact(runId, allocationId, schoolId, "fee_invoice_carried",
                (UUID) row[0], (String) row[2]);
        }
        return rounded;
    }

    /** One head, made once per school, so the opening balance is a real fee line. */
    private UUID arrearsHead(UUID schoolId) {
        List<UUID> existing = jdbc.query(
            "SELECT id FROM fee_head WHERE school_id = ? AND code = ?",
            (rs, i) -> UUID.fromString(rs.getString("id")), schoolId, ARREARS_HEAD_CODE);
        if (!existing.isEmpty()) return existing.get(0);
        UUID id = UUID.randomUUID();
        jdbc.update(
            "INSERT INTO fee_head (id, school_id, code, name, is_recurring, gst_rate_pct) " +
            "VALUES (?, ?, ?, ?, FALSE, 0)",
            id, schoolId, ARREARS_HEAD_CODE, "Arrears carried forward");
        return id;
    }

    /**
     * The bus seat moves with the child: the old assignment ends with the year
     * and a new one starts with the next, at whatever the route charges then.
     * A graduating child's assignment is ended and not replaced, which is what
     * keeps them off next year's manifest (GRAD-06).
     */
    public int carryTransport(UUID runId, UUID allocationId, UUID schoolId, UUID studentId,
                              AcademicYearDto from, AcademicYearDto to, boolean createNext) {
        var live = jdbc.query(
            "SELECT id, route_id, stop_id FROM student_transport " +
            "WHERE student_id = ? AND (ends_on IS NULL OR ends_on >= ?)",
            (rs, i) -> new Object[]{
                UUID.fromString(rs.getString("id")),
                UUID.fromString(rs.getString("route_id")),
                UUID.fromString(rs.getString("stop_id"))
            },
            studentId, Date.valueOf(from.endsOn()));

        int carried = 0;
        for (Object[] row : live) {
            jdbc.update("UPDATE student_transport SET ends_on = ? WHERE id = ?",
                Date.valueOf(from.endsOn()), row[0]);
            repo.recordArtifact(runId, allocationId, schoolId, "student_transport_closed",
                (UUID) row[0], "ends_on");
            if (!createNext) continue;

            UUID newId = UUID.randomUUID();
            jdbc.update(
                "INSERT INTO student_transport (id, school_id, student_id, route_id, stop_id, starts_on) " +
                "VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT (student_id, route_id, starts_on) DO NOTHING",
                newId, schoolId, studentId, row[1], row[2], Date.valueOf(to.startsOn()));
            repo.recordArtifact(runId, allocationId, schoolId, "student_transport", newId, null);
            carried++;
        }
        return carried;
    }

    /**
     * Elective continuity: a child who took Physics this year takes it next
     * year unless somebody changes it. The election is re-recorded against the
     * new enrolment because {@code student_subject} hangs off the enrolment,
     * not the student — last year's row would otherwise resolve to last year's
     * class list.
     */
    public int carryElectives(UUID runId, UUID allocationId, UUID schoolId, UUID fromEnrolmentId,
                              UUID newEnrolmentId, AcademicYearDto to) {
        var elections = jdbc.query(
            "SELECT subject_id, elective_group_id FROM student_subject " +
            "WHERE enrolment_id = ? AND status = 'elected'",
            (rs, i) -> new Object[]{
                UUID.fromString(rs.getString("subject_id")),
                rs.getString("elective_group_id") == null ? null
                    : UUID.fromString(rs.getString("elective_group_id"))
            },
            fromEnrolmentId);

        int carried = 0;
        for (Object[] row : elections) {
            UUID id = UUID.randomUUID();
            // The option block belongs to a grade *and* a year, so last year's
            // block is not this year's: the subject carries, the block does not.
            jdbc.update(
                "INSERT INTO student_subject (id, school_id, enrolment_id, subject_id, status, effective_from) " +
                "VALUES (?, ?, ?, ?, 'elected', ?)",
                id, schoolId, newEnrolmentId, row[0], Date.valueOf(to.startsOn()));
            repo.recordArtifact(runId, allocationId, schoolId, "student_subject", id, null);
            carried++;
        }
        return carried;
    }
}
